from typing import Optional, List, Set
from rdflib import Graph, Namespace, RDF, URIRef, DCTERMS

from . import query

from .header import build_page_header

HYDRA = Namespace("http://www.w3.org/ns/hydra/core#")
DCAT = Namespace("http://www.w3.org/ns/dcat#")


PREFIX_HACK = True # assumes shapes generated by shape-gen service

def build_page_complete(page : int, modified_since : Optional[str]) -> Graph :
    # queries for header
    total_datasets = query.total_datasets(modified_since)
    # TODO just use length here
    ds_uris : List[str] = query.datasets_for_page(page, modified_since) 
    # actual header
    header : Graph = build_page_header(page, modified_since, total_datasets, ds_uris)

    # queries for body
    # datasets = ((uri, query.dataset_graph(uri)) for uri in ds_uris)
    # actual body
    body = Graph()

    index = 0 # just used for serialiazation

    for ds_graph in ( query.dataset_graph(ds_uri) for ds_uri in ds_uris ) :

        # dataset graph
        body += ds_graph

        # nice namespaces
        annotated_uris : Set[str] = { str(s) for s in ds_graph.subjects(DCTERMS.conformsTo) if isinstance(s, URIRef) }
        for annotated_uri in annotated_uris :
            # nice prefixes for the shacl-graph that was just added
            base = f"{annotated_uri}/auto-generated-shapes/"
            first_obj = str(next(ds_graph.objects(URIRef(annotated_uri), DCTERMS.conformsTo)))
            uuid = first_obj[len(base):].split("/")[0]
            body.bind(f"shapes-{index}", URIRef(f"{base}{uuid}/"))
            body.bind(f"shapes-{index}-bn", URIRef(f"{base}{uuid}/bnodes/"))
            index += 1

        # actually adding shape graphs
        if PREFIX_HACK :
            for annotated_uri in annotated_uris :
                body += query.shapes_graph(annotated_uri)

        else : # better approach (to get ...)
            nodeshape_uris : List[str] = [ str(o) for o in ds_graph.objects(None, DCTERMS.conformsTo) if isinstance(o, URIRef) ]
            if nodeshape_uris :
                body += query.span_nodeshapes(nodeshape_uris)

    return header + body